# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "node"
  config.vm.provider "libvirt" do |l|
    l.memory = 256
    l.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
  SHELL
end
