Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "gitlab"
  config.vm.hostname = "gitlab.example.com"
  config.vm.provision "shell", inline: <<-SCRIPT
    echo 'root:vagrant' | chpasswd
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    yum install -y curl policycoreutils openssh-server openssh-clients
    systemctl enable sshd
    systemctl start sshd
    yum install -y postfix
    systemctl enable postfix
    systemctl start postfix
    firewall-cmd --permanent --add-service=http
    systemctl reload firewalld
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
    yum install -y gitlab-ce
    gitlab-ctl reconfigure
  SCRIPT
  config.vm.provider "libvirt" do |l|
    l.memory = 1024
    l.cpus = 1
  end
end
