Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.66.66"
  config.vm.define "gitlab"
  config.vm.hostname = "gitlab.example.com"
  config.vm.provider "libvirt" do |l|
    l.memory = 1024
    l.cpus = 1
  end
end
