# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "jenkins"
  config.vm.hostname = "jenkins.example.com"
  config.vm.provider "libvirt" do |l|
    l.memory = 2048
    l.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SCRIPT
    echo 'root:vagrant' | chpasswd
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    yum install -y git
    #docker
    yum install -y yum-utils
    yum-config-manager \
    --add-repo \
    https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
    yum -y install docker-engine
    systemctl enable docker
    systemctl start docker
    groupadd docker
    usermod -aG docker $(whoami)
    #chef
    curl "https://packages.chef.io/files/stable/chefdk/1.2.20/el/7/chefdk-1.2.20-1.el7.x86_64.rpm" -o "chef.rpm"
    rpm -ivh chef.rpm
    #jenkins
    yum -y install java
    yum -y install bind-utils
    yum install -y wget
    wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    yum -y install jenkins
    systemctl start jenkins.service
    systemctl status jenkins.service
  SCRIPT
end
