# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "chef"
  config.vm.provider "libvirt" do |l|
    l.memory = 2048
    l.cpus = 2
  end
end
